import type { NextPage } from "next";
import Head from "next/head";
import Hello from "../components/Hello";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-red-300">Hello Next.js</h1>
        <Hello />
      </main>

      <footer>
        <h3>Footer</h3>
      </footer>
    </div>
  );
};

export default Home;
